stages:
  scanpy:
    cmd: python scripts/run_scanpy.py
    deps:
    - scripts/run_scanpy.py
    - src/scrnaseq_lightgbm/preprocessing/scanpy_pipeline.py
    params:
    - scanpy
    - paths
    outs:
    - data/processed/processed.h5ad
  lightgbm:
    cmd: python scripts/run_lightgbm.py
    deps:
    - data/processed/processed.h5ad
    - scripts/run_lightgbm.py
    - src/scrnaseq_lightgbm/models/lightgbm_pipeline.py
    params:
    - lightgbm
    - evaluation
    - paths
    outs:
      - artifacts/models/lightgbm_model.txt
      - data/processed/annotated.h5ad
    metrics:
      - artifacts/metrics/metrics.json
  visualize:
    cmd: python scripts/plot_umap.py
    deps:
    - data/processed/annotated.h5ad
    - scripts/plot_umap.py
    outs:
    - artifacts/figures
